language: minimal
os: linux
dist: bionic

addons:
  apt:
    packages:
    - cmake
    - clang

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug
- cd ..
- make -C build
- make -C bpfinst-spec/tests
